#!/usr/bin/python
"""
 * Copyright (C) 2015 Alessandro Torre alessandro.torrebo@gmail.com
 *
 *
 * This module print on video, write on pause.txt and send an alert email when e_check set pause
 *
 ******************************************************************************
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 *
 * THE AUTHORS OF THIS PROGRAM ACCEPT ABSOLUTELY NO LIABILITY FOR
 * ANY HARM OR LOSS RESULTING FROM ITS USE.  IT IS _EXTREMELY_ UNWISE
 * TO RELY ON SOFTWARE ALONE FOR SAFETY.  Any machinery capable of
 * harming persons must have provisions for completely removing power
 * from all motors, etc, before persons enter any danger area.  All
 * machinery must be designed to comply with local and national safety
 * codes, and the authors of this software can not, and do not, take
 * any responsibility for such compliance.
 *
 * This code was written as part of the machinekit project.  For more
 * information, go to www.machinekit.io
"""

import smtplib
import hal 
import time
e_alert = hal.component("e_alert")
e_alert.newpin("cmd_x",		 hal.HAL_FLOAT, hal.HAL_IN)
e_alert.newpin("cmd_y",		 hal.HAL_FLOAT, hal.HAL_IN)
e_alert.newpin("cmd_z",		 hal.HAL_FLOAT, hal.HAL_IN)
e_alert.newpin("cmd_a",		 hal.HAL_FLOAT, hal.HAL_IN)
e_alert.newpin("program_line",	 hal.HAL_S32, hal.HAL_IN)
e_alert.newpin("steps_failed",	 hal.HAL_FLOAT, hal.HAL_IN)
e_alert.newpin("write_send",	 hal.HAL_BIT, hal.HAL_IO)
#e_alert.newpin("", 		 hal.HAL_FLOAT, hal.HAL_OUT)
e_alert.ready()	
try:
	while 1:
		while e_alert.write_send==1:
			time.sleep(1)
			
# Open a file in write mode
			fo = open("/home/machinekit/linuxcnc/configs/ARM.BeagleBone.CRAMPS-mouse/pause.txt", "rw+")
			#if (fo == NULL) printf "Error opening 'pause.txt' file!";
			#else printf(fd,"Pause by e_check in x=%5.3f y=%5.3f z=%5.3f a=%5.3f program.line =%5.3f steps.failed =%5.3f\r",cmd_x,cmd_y,cmd_z,cmd_a,program_line,steps_failed);
			print "Pause by e_check in x= ",e_alert.cmd_x," y= ",e_alert.cmd_y," z= ",e_alert.cmd_z," a= ",e_alert.cmd_a," program.line = ",e_alert.program_line," steps.failed = ",e_alert.steps_failed
			fo.write( "Pause by e_check in:\r\n\nx=%5.3f y=%5.3f z=%5.3f a=%5.3f\r\n\nprogram.line=%5.3f steps.failed=%5.3f\r\n"%(e_alert.cmd_x, e_alert.cmd_y, e_alert.cmd_z, e_alert.cmd_a, e_alert.program_line, e_alert.steps_failed)) 
			fo.truncate()	
			fo.close()

# Send an alert mail	
			from email.MIMEMultipart import MIMEMultipart
			from email.MIMEText import MIMEText
			from email.MIMEBase import MIMEBase
			from email import encoders
 
			fromaddr = "WRITE YOUR EMAIL"
			toaddr = "WRITE YOUR EMAIL"
 
			msg = MIMEMultipart()
 
			msg['From'] = fromaddr
			msg['To'] = toaddr
			msg['Subject'] = "e_check pause"
 
			body = "ICON5D Pause for filament e_check"
		 
			msg.attach(MIMEText(body, 'plain'))
	 
			filename = "pause.txt"
			attachment = open("/home/machinekit/linuxcnc/configs/ARM.BeagleBone.CRAMPS-mouse/pause.txt", "rb")
 
			part = MIMEBase('application', 'octet-stream')
			part.set_payload((attachment).read())
			encoders.encode_base64(part)
			part.add_header('Content-Disposition', "attachment; filename= %s" % filename)
 
			msg.attach(part)
 
			server = smtplib.SMTP('smtp.gmail.com', 587)
			server.starttls()
			server.login(fromaddr, "WRITE YOUR PASSWORD")
			text = msg.as_string()
			server.sendmail(fromaddr, toaddr, text)
			server.quit()
	
			e_alert['write_send'] = 0
except KeyboardInterrupt:
	raise SystemExit
# http://naelshiab.com/tutorial-send-email-python/
#http://linuxcnc.org/docs/html/hal/halmodule.html
